ablog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('theblog.urls')),
    path('members/',include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path, include
from .views import UserRegisterView, UserEditView, PasswordsChangeView
from django.contrib.auth import views as auth_views

app_name = 'members'
urlpatterns = [
	path('register/',UserRegisterView.as_view(),name='register'),
	path('edit_profile/',UserEditView.as_view(),name='edit-profile'),
	# path('password/',auth_views.PasswordChangeView.as_view(template_name='registration/change_password.html')),
	path('password/',PasswordsChangeView.as_view(), name='change-password'),
]

theblog/urls.py
from . import views
from django.urls import path
from theblog.views import (PostListView, PostDetailView, PostCreateView, 
	PostUpdateView, PostDeleteView, CategoryCreateView, Category2CreateView)

app_name = 'theblog'
urlpatterns = [

    path('',PostListView.as_view(), name='home'),
    path('post-detail/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('add-category/', CategoryCreateView.as_view(), name='add-category'),
    path('add-post/', PostCreateView.as_view(), name='add-post'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='update-post'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete-post'),
    path('create-category/', CategoryCreateView.as_view(), name='create-category'),
    
    path('create-category2/', Category2CreateView.as_view(), name='create-category2'),
    
    path('category/<str:cats>/', views.CategoryView, name='category'),
    path('like/<int:pk>', views.LikeView, name='like-post'),

    path('datetime/', views.current_datetime, name='date-time')
]

theblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
	bio = models.TextField()

	def __str__(self):
		return str(self.user)

class Category(models.Model):
	name=models.CharField(max_length=255)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('theblog:add-post')

class Category_2(models.Model):
	name = models.CharField(max_length=255)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('theblog:add-post')

class Post(models.Model):
	title = models.CharField(max_length=255)
	header_image = models.ImageField(null=True, blank=True, upload_to='images/')
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	body = RichTextField(blank = True, null=True)
	# body = models.TextField()
	category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
	post_date = models.DateField(auto_now_add=True)
	category_2 = models.CharField(max_length=255, default='coding')
	snippet = models.CharField(max_length=255, default='click to read more...')
	likes = models.ManyToManyField(User, related_name='blog_posts', null=True)

	def total_likes(self):
		return self.likes.count()

	def __str__(self):
		return self.title + '|' + str(self.author)

	def get_absolute_url(self):
		return reverse('theblog:home')

theblog/forms.py
from django import forms
from .models import Category, Post, Category_2

#coding,coding, sports, sports
cats = Category_2.objects.all().values_list('name','name')
cat_list=[]

for item in cats:
	cat_list.append(item)

class PostForm(forms.ModelForm):
	class Meta:
		model = Post

		fields = ['category_2','title','author','body', 'header_image']

		widgets = {
			# 'category':forms.Select(attrs={'class':'form-control'}),
			'category_2':forms.Select(choices = cat_list, attrs={'class':'form-control'}),
			'title':forms.TextInput(attrs={'class':'form-control'}),
			'author':forms.TextInput(attrs={'class':'form-control','value':'','id':'elder','type':'hidden'}),
			# 'author':forms.Select(attrs={'class':'form-control'}),
			'body':forms.Textarea(attrs={'class':'form-control'}),
		}



# class UpdateForm(forms.ModelForm):
# 	class Meta:
# 		model = Post
# 		fields = ['category','title','body']

# 		widgets = {
# 			'category':forms.Select(attrs={'class':'form-control'}),
# 			'title':forms.TextInput(attrs={'class':'form-control'}),
# 			'body':forms.Textarea(attrs={'class':'form-control'}),
# 		}

theblog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404 , HttpResponseRedirect
from django.views.generic import (ListView, DetailView, CreateView, UpdateView, DeleteView)
from .models import Category, Post, Category_2
from .forms import PostForm
from django.urls import reverse_lazy, reverse
from django.contrib import messages
import datetime

def current_datetime(request):
	now = datetime.datetime.now()
	html = "<html><body>It is now %s.</body></html" % now
	return HttpResponse(html)


def CategoryView(request, cats):
		category_posts = Post.objects.filter(category_2=cats)
		cat_menu = Category_2.objects.all()
		return render(request,'theblog/category.html', {'cats':cats,'category_posts':category_posts,'cat_menu':cat_menu})

def LikeView(request, pk):
	post = get_object_or_404(Post, id=request.POST.get('post_id'))
	liked = False
	if post.likes.filter(id=request.user.id).exists():
		post.likes.remove(request.user)
		liked = False
		messages.warning(request, f'You have unliked a page')
	else:
		post.likes.add(request.user)
		liked = True
		messages.success(request, f'You have liked a page')
	return HttpResponseRedirect(reverse('theblog:post-detail',args=[str(pk)]))
	# return HttpResponseRedirect(reverse('theblog:home'))



class CategoryCreateView(CreateView):
	model = Category
	# form_class = PostForm
	template_name = 'theblog/ad_category.html'
	fields = '__all__'



class PostListView(ListView):
	model = Post
	template_name = 'theblog/home.html'
	ordering = ['-post_date']

	def get_context_data(self, *args, **kwargs):
		cat_menu = Category_2.objects.all()
		context = super(PostListView, self).get_context_data(*args, **kwargs)
		context["cat_menu"] = cat_menu
		return context

class PostDetailView(DetailView):
	model = Post
	template_name = 'theblog/post_detail.html'

	def get_context_data(self, *args, **kwargs):
		cat_menu = Category_2.objects.all()
		context = super(PostDetailView, self).get_context_data(*args, **kwargs)
		stuff = get_object_or_404(Post,id=self.kwargs['pk'])
		total_likes = stuff.total_likes()

		liked = False

		if stuff.likes.filter(id=self.request.user.id).exists():
			liked = True
		context["cat_menu"] = cat_menu
		context["total_likes"] = total_likes
		context["liked"] = liked
		return context	

class Category2CreateView(CreateView):
	model = Category_2
	# form_class = PostForm
	template_name = 'theblog/add_category2.html'
	fields = '__all__'

class PostCreateView(CreateView):
	model = Post
	form_class = PostForm
	template_name = 'theblog/add_post.html'

	def get_context_data(self, *args, **kwargs):
		cat_menu = Category_2.objects.all()
		context = super(PostCreateView, self).get_context_data(*args, **kwargs)
		context["cat_menu"] = cat_menu
		return context	



class PostUpdateView(UpdateView):
	model = Post
	# form_class = UpdateForm
	template_name = 'theblog/update_post.html'
	form_class = PostForm


class PostDeleteView(DeleteView):
	model = Post
	# form_class = UpdateForm
	template_name = 'theblog/delete_post.html'
	success_url = reverse_lazy('theblog:home')
	success_message = "Post was deleted successfully."

	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(PostDeleteView, self).delete(request, *args, **kwargs)
	# success_url = reverse_lazy('theblog:home')
# def detail(request, post_id):
# 	try:
# 		post = Post.objects.get(pk=post_id)
# 	except Post.DoesNotExist:
# 		raise Http404('Post does not exist')
# 	return render(request, 'theblog/post_detail.html', {'post':post})

theblog/templates/theblog/add_category.html
{% extends 'theblog/base.html' %}
{% block title%}Home Page{% endblock %}
{% block content %}

<div class="container">
	<div class="mx-auto" style="width: 600px;">
		<h1 class="mt-4">Add Category</h1>
		<div class="form-group">
			<form method="POST">{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-primary">Add</button>
			</form>
		</div>
	</div>
</div>
	
	
	
{% endblock %}	
</body>
</html>

theblog/templates/theblog/add_category2.html
{% extends 'theblog/base.html' %}
{% block title%}Home Page{% endblock %}
{% block content %}

<div class="container">

	<h1 class="mt-4">Adding Category2</h1>
	<div class="form-group">
		<form method="POST">{% csrf_token %}
			{{ form.as_p }}
		<button class="btn btn-primary">Add</button>
		</form>
	</div>
	
</div>
	
	
	
{% endblock %}	
</body>
</html>

theblog/templates/theblog/add_post.html
{% extends 'theblog/base.html' %}
{% block title%}Home Page{% endblock %}
{% block content %}

<div class="container">
	<div class="mx-auto" style="width: 600px;">
	<h1 class="mt-4">Adding Post</h1>

		<div class="form-group">
			<form method="POST" enctype="multipart/form-data">{% csrf_token %}
				{{ form.media }}
				{{ form.as_p }}
				
			<button class="btn btn-primary">Add</button>
			</form>
			<script type="text/javascript">
				var name = "{{ user.id }}";
				document.getElementById("elder").value = name;

			</script>
		</div>
	</div>
</div>
	
	
	
{% endblock %}	
</body>
</html>

theblog/templates/theblog/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  
  <link rel="stylesheet" type="text/css" href="{% static 'theblog/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'theblog:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>

          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if cat_menu %}
            {% for item in cat_menu %}
            <a class="dropdown-item" href="{% url 'theblog:category' item %}"> {{ item }}</a>
            {% endfor %}
          </div>
          {% endif %}
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'theblog:create-category2' %}">Add Category</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'theblog:add-post' %}">Add Post</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'members:edit-profile' %}">Edit Profile</a>
         
       </li>
        <li class="nav-item">
         
         <a class="nav-link" href="{% url 'logout' %}">Logout</a>
       </li>
       {% else %}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'members:register' %}">Register</a>
        </li>
      <li class="nav-item">
       <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
     {% endif %}

      
      </ul>
    </div>
</nav>
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}
  <div class="mx-auto mt-5" style="width: 1000px;">
<div class="container">

  {% block content %}
      



  {% endblock %}
</div>
</div>	

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

theblog/templates/theblog/category.html
{% extends 'theblog/base.html' %}
{% block title%}Category Page{% endblock %}
{% block content %}

		
		<h1>Categories : {{ cats }}</h1>
		{% for post in category_posts %}

			<div class="card">
			  <div class="card-header">
			    Author: {{ post.author.first_name }} {{ post.author.last_name }}
			  </div>
			  <div class="card-body">
			    <h5 class="card-title">{{ post.title }}</h5>
			    <p class="card-text">{{ post.body }}</p>
			    {% if user.id == post.author.id %}
			    <a href="{% url 'theblog:update-post' post.pk %}" class="card-link btn btn-primary mx-auto">Edit</a>
				<a href="{% url 'theblog:delete-post' post.pk %}" class="card-link btn btn-danger mx-auto">Delete</a>
				{% endif %}
			  </div>
			</div>
		
			
			
		{% endfor %}
		
		
	  	
	

	
{% endblock %}	

theblog/templates/theblog/delete_post.html
{% extends 'theblog/base.html' %}
{% block title%}Home Page{% endblock %}
{% block content %}

<div class="container">
	<div class="mx-auto" style="width: 600px;">
	{% if user.is_authenticated %}
	<h1 class="mt-4">Delete Post...</h1>
	<ul>
		
			<li>Category : {{ post.category }}</li>
			<ul>
				<li>Post title: {{ post.title }}</li>
				<li>Post body: {{ post.body }}</li>
				<li>Post Author: {{ post.author.first_name }} {{ post.author.last_name }}</li>
			</ul>
			
		
	</ul>
	<div class="form-group">
		<form method="POST">{% csrf_token %}
			{{ form.as_p }}
		<button class="btn btn-danger">Delete</button>
		</form>
	</div>
	{% else %}
		<h2>Please login to do that.</h2>
	{% endif %}
	</div>
</div>
	
	
	
{% endblock %}	
</body>
</html>

theblog/templates/theblog/home.html
{% extends 'theblog/base.html' %}
{% block title%}Home Page{% endblock %}
{% block content %}
	
{% for post in object_list %}

	<div class="card bg-light mb-3 mt-4" style="width: 18rem;">
	
	  	<div class="card-body">

	    <h5 class="card-title"><a href="{% url 'theblog:category' post.category_2 %}">Category : {{ post.category_2 }}</a></h5>
	    <h6 class="card-subtitle mb-2 text-muted mt-3">
	    	<a href="{% url 'theblog:post-detail' post.pk %}">Post title: {{ post.title }}</a></h6>
<!-- 	 	<p class="card-text">Post body: {{ post.snippet }}</p> -->
	    <p class="card-text">Post body: {{ post.body|truncatechars:70|safe }}</p>
	    {% if user.id == post.author.id %}
	    <a href="{% url 'theblog:update-post' post.pk %}" class="card-link">Edit Post</a>
	    {% endif %}
	    <a href="#" class="card-link mt-3">Post Author: {{ post.author.first_name }} {{ post.author.last_name }}</a>
	  	</div>
	</div>

{% endfor %}

{% endblock %}	

theblog/templates/theblog/post_detail.html
{% extends 'theblog/base.html' %}
{% block title%}Detail Page{% endblock %}
{% block content %}

	

<div class="card">
  <h5 class="card-header">Category : {{ post.category }}</h5>
  <div class="card-body">
    <h5 class="card-title">Post title: {{ post.title }}</h5>
    {% if post.header_image %}
    	<img src="{{post.header_image.url}}">
    {% endif %}
    <p class="card-text">Post body: {{ post.body }} </p>
    <p>Post Author: {{ post.author.first_name }} {{ post.author.last_name }}</p>
    {% if user.is_authenticated %}
	{% if user.id == post.author.id %}
		<form action="{% url 'theblog:like-post' post.pk %}" method="POST" class="mb-2">
			{% csrf_token %}
			{% if liked %}
			<button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-danger btn-sm">Unlike</button> ({{ total_likes }} likes)
		
			{% else %}
			<button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary btn-sm">Like</button> ({{ total_likes }} likes)
			{% endif %}
		</form>
		
		<a href="{% url 'theblog:update-post' post.pk %}" class="card-link btn btn-primary">Edit</a>
		<a href="{% url 'theblog:delete-post' post.pk %}" class="card-link btn btn-danger">Delete</a>
	{% endif %}
  </div>
</div>

	{% else %}
	<small>Please <a href="{% url 'login' %}">login</a> to comment a like.</small>
	{% endif %}

{% endblock %}	
</body>
</html>

theblog/templates/theblog/update_post.html
{% extends 'theblog/base.html' %}
{% block title%}Home Page{% endblock %}
{% block content %}

<div class="container">

		{% if user.is_authenticated %}
			<h1 class="mt-4">Update Post</h1>
			
		<div class="form-group">
				<form method="POST">{% csrf_token %}
					{{ form.media }}
					{{ form.as_p }}
					
				<button class="btn btn-primary">Update</button>
			</form>
		</div>
		{% else %}
		<h2>Please login to do that.</h2>
		{% endif %}
	
</div>
	
	
	
{% endblock %}	
</body>
</html>